### ISSUE TITLE
[FEATURE] Possible to use other FlatList props

### ISSUE THREAD

**Issue by anthlasserre** [Thanasis1101/react-native-gif-search#1]
- Possibility to use other FlatList props like `numColumns`
- Use Mansory List Grid https://github.com/AppAndFlow/react-native-masonry-list

**Comment by Thanasis1101** [comment]
Thank you for your suggestion ! Hope you enjoy the package.
I see it could be useful to render multiple columns so what I suggest is that I add a property `numColumns` in the `GifSearch` component. For using other properties of the FlatList I could add a property `gifListProps` in case someone needs something extra, although I am not sure how useful it would be.
Regarding mansory list grid, I am not convinced how it would be useful. I think the above can be implemented using simple FlatList.

**Comment by anthlasserre** [comment]
@Thanasis1101 Okey we can start improve with numColumns and extra props firstly. And next we will see how to render more properly Giphy components.

**Comment by Thanasis1101** [comment]
@anthlasserre Great !
