### ISSUE TITLE
Animation aren't playing

### ISSUE THREAD

**Issue by dreamerchandra** [Thanasis1101/react-native-gif-search#13]
I added
```
    implementation 'com.facebook.fresco:fresco:2.0.0'
    implementation 'com.facebook.fresco:animated-gif:2.0.0'
```
Did `./gradlew clean ` and did `react-native run-android`? Still not working.
Also uninstalled the app also did `yarn start --reset-cache` still not hope?

**Comment by Thanasis1101** [comment]
@dreamerchandra Which React Native version do you use? Because for RN < 0.60 you need different versions for the dependencies. E.g. for RN 0.59 you need version 1.10.0 (as you can see [here](https://archive.reactnative.dev/docs/image#gif-and-webp-support-on-android)).

**Comment by dreamerchandra** [comment]
Fixed it...
I'm using RN 0.65+
For this, you should [use](https://stackoverflow.com/a/69208513/5277189)
```
    implementation 'com.facebook.fresco:fresco:2.5.0'
    implementation 'com.facebook.fresco:animated-gif:2.5.0'
```

Please update read me for instructions... it's pretty horrible I was literally clueless for 2 days.

**Comment by Thanasis1101** [comment]
@dreamerchandra Great ! Thanks for the feedback !
